workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 120
    environment:
      vars: {}
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          cd ios && pod install && cd ..
          # XCWorkspaceの存在を確認（デバッグ用）
          ls -la ios/
      - name: Build for iOS simulator
        script: |
          cd ios
          # ここでXCWorkspaceの名前を確認
          WORKSPACE_NAME=$(ls | grep xcworkspace | head -n 1)
          echo "Found workspace: $WORKSPACE_NAME"
          
          # 正しいWorkspace名を使用
          xcodebuild \
            -workspace $WORKSPACE_NAME \
            -scheme BookApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest' \
            build
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app