workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build for iOS simulator
        script: |
          xcodebuild \
            -workspace ios/BookApp.xcworkspace \
            -scheme BookApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -derivedDataPath build/ios \
            build
    artifacts:
      - build/ios/Build/Products/Debug-iphonesimulator/*.app
