workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 120
    environment:
      vars: {}
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies and build iOS
        script: |
          yarn install
          cd ios && pod install
          cd ..
          npx react-native run-ios --no-packager --simulator="iPhone 14"
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app